---
- name: Install Docker and Docker Compose on Ubuntu
  hosts: 23.88.54.223
  become: true
  become_method: sudo

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker service is running and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      shell: >
        curl -sSL https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
      args:
        executable: /bin/bash

    - name: Install sqitch
      apt: 
        name: sqitch
        state: present

    - name: Install nginx
      apt: 
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx is started and enabled on boot
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install Certbot dependencies
      ansible.builtin.apt:
        name:
          - software-properties-common
        state: present

    - name: Install Certbot for Nginx
      ansible.builtin.apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: present

    - name: Obtain and install Let's Encrypt certificate
      ansible.builtin.command:
        cmd: certbot --nginx --non-interactive --agree-tos --email boudewijn@hello-data.nl -d theridiid.net
        creates: /etc/letsencrypt/live/theridiid.net/fullchain.pem

    - name: Add Ondřej Surý PPA
      apt_repository:
        repo: ppa:ondrej/php
        state: present
      when: ansible_os_family == "Debian"
      
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PHP 8.2 and common extensions
      apt:
        name:
          - php8.2
          - php8.2-cli
          - php8.2-fpm
          - php8.2-common
          - php8.2-mysql
          - php8.2-zip
          - php8.2-gd
          - php8.2-mbstring
          - php8.2-curl
          - php8.2-xml
          - php8.2-bcmath
          - php8.2-tokenizer
          - php8.2-ctype
          - php8.2-opcache
          - php8.2-iconv
        state: present

    - name: Install composer
      ansible.builtin.shell: >
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      args:
        executable: /bin/bash

    - name: Install Node.js
      ansible.builtin.shell: >
        curl -sS https://deb.nodesource.com/setup_20.x | sudo -E bash - && sudo apt-get install -y nodejs
   
  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
    
